In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("cleaning_ex4.csv")

In [4]:
df.head()

id                               name  host_id   host_name  \
0  27934.0    Nice room with superb city view   120437      Nuttee   
1  27979.0     Easy going landlord,easy place   120541         Emy   
2  28745.0  modern-style apartment in Bangkok   123784  Familyroom   
3  47516.0         Beautiful waterfront house   214456    Anuradha   
4  48736.0    Condo with Chaopraya River View   222005    Athitaya   

  neighbourhood  latitude  longitude        room_type   price  minimum_nights  \
0   Ratchathewi  13.75983  100.54134  Entire home/apt  1595.0              15   
1       Bang Na  13.66818  100.61674     Private room     NaN               1   
2     Bang Kapi  13.75232  100.62402     Private room     NaN              60   
3    Don Mueang  13.92726  100.58529  Entire home/apt  4188.0               3   
4    Rat Burana  13.68556  100.49535     Private room  1450.0              14   

   number_of_reviews last_review  reviews_per_month  \
0                 65  17-09-2024               0.40   
1                  0         NaN                NaN   
2                  0         NaN                NaN   
3                  0         NaN                NaN   
4                  1  03-02-2014               0.01   

   calculated_host_listings_count  availability_365  number_of_reviews_ltm  
0                               1               362                      0  
1                               2                 0                      0  
2                               1                 0                      0  
3                               1               365                      0  
4                               1               365                      0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28806 entries, 0 to 28805
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              28806 non-null  float64
 1   name                            28806 non-null  object 
 2   host_id                         28806 non-null  int64  
 3   host_name                       28797 non-null  object 
 4   neighbourhood                   28806 non-null  object 
 5   latitude                        28806 non-null  float64
 6   longitude                       28806 non-null  float64
 7   room_type                       28806 non-null  object 
 8   price                           23273 non-null  float64
 9   minimum_nights                  28806 non-null  int64  
 10  number_of_reviews               28806 non-null  int64  
 11  last_review                     18716 non-null  object 
 12  reviews_per_month               

In [6]:
df["price"].unique()

array([1595.,   nan, 4188., ..., 4798., 2775., 5424.])

In [17]:
avg_price=df.loc[df["price"]!='nan',"price"].mean().round(2)
avg_price

np.float64(2528.75)

In [18]:
df["price"]=df["price"].fillna(avg_price)

In [19]:
df["price"].unique()

array([1595.        , 2528.74915138, 4188.        , ..., 4798.        ,
       2775.        , 5424.        ])

In [20]:
df["reviews_per_month"].unique()

array([4.000e-01,       nan, 1.000e-02, 2.200e-01, 8.600e-01, 1.900e-01,
       5.700e-01, 4.600e-01, 1.800e-01, 3.400e-01, 4.500e-01, 6.100e-01,
       2.480e+00, 5.000e-01, 1.410e+00, 2.980e+00, 2.900e-01, 2.300e-01,
       9.000e-02, 2.400e+00, 2.700e-01, 8.300e-01, 2.100e-01, 3.800e-01,
       5.000e-02, 7.400e-01, 4.200e-01, 1.000e-01, 4.400e-01, 1.400e-01,
       9.500e-01, 2.900e+00, 1.550e+00, 9.800e-01, 3.000e-02, 4.000e-02,
       2.400e-01, 2.000e-02, 6.400e-01, 2.000e-01, 1.200e-01, 3.000e-01,
       1.700e-01, 2.560e+00, 2.020e+00, 1.600e-01, 6.000e-02, 8.000e-02,
       6.000e-01, 8.900e-01, 9.400e-01, 2.500e+00, 7.100e-01, 3.440e+00,
       6.800e-01, 3.780e+00, 2.520e+00, 3.500e-01, 1.350e+00, 5.400e-01,
       5.200e+00, 1.100e-01, 8.500e-01, 1.590e+00, 1.100e+00, 9.600e-01,
       1.220e+00, 1.040e+00, 5.100e-01, 1.500e-01, 7.000e-02, 2.100e+00,
       3.300e-01, 5.800e-01, 2.240e+00, 1.720e+00, 1.580e+00, 1.660e+00,
       1.500e+00, 1.300e-01, 1.060e+00, 1.110e+00, 

In [21]:
df["reviews_per_month"]=df["reviews_per_month"].fillna(0.0)

In [22]:
df["reviews_per_month"].unique()

array([4.000e-01, 0.000e+00, 1.000e-02, 2.200e-01, 8.600e-01, 1.900e-01,
       5.700e-01, 4.600e-01, 1.800e-01, 3.400e-01, 4.500e-01, 6.100e-01,
       2.480e+00, 5.000e-01, 1.410e+00, 2.980e+00, 2.900e-01, 2.300e-01,
       9.000e-02, 2.400e+00, 2.700e-01, 8.300e-01, 2.100e-01, 3.800e-01,
       5.000e-02, 7.400e-01, 4.200e-01, 1.000e-01, 4.400e-01, 1.400e-01,
       9.500e-01, 2.900e+00, 1.550e+00, 9.800e-01, 3.000e-02, 4.000e-02,
       2.400e-01, 2.000e-02, 6.400e-01, 2.000e-01, 1.200e-01, 3.000e-01,
       1.700e-01, 2.560e+00, 2.020e+00, 1.600e-01, 6.000e-02, 8.000e-02,
       6.000e-01, 8.900e-01, 9.400e-01, 2.500e+00, 7.100e-01, 3.440e+00,
       6.800e-01, 3.780e+00, 2.520e+00, 3.500e-01, 1.350e+00, 5.400e-01,
       5.200e+00, 1.100e-01, 8.500e-01, 1.590e+00, 1.100e+00, 9.600e-01,
       1.220e+00, 1.040e+00, 5.100e-01, 1.500e-01, 7.000e-02, 2.100e+00,
       3.300e-01, 5.800e-01, 2.240e+00, 1.720e+00, 1.580e+00, 1.660e+00,
       1.500e+00, 1.300e-01, 1.060e+00, 1.110e+00, 

In [23]:
df["reviews_per_month"]=df["reviews_per_month"].astype(int)

In [24]:
df["reviews_per_month"].unique()

array([ 0,  2,  1,  3,  5,  4,  8,  9, 30, 18, 16,  6, 13,  7, 23, 22, 26,
       20, 44, 57, 11, 10, 36, 17, 19, 24, 28, 14, 34, 12])

In [25]:
df.loc[df["number_of_reviews"]>100,:]

id                                               name  \
7      1.050420e+05                Central Bangkok 3 Bedroom Apartment   
21     3.851300e+05         Lumphini 4 City Center | Private Bath | AC   
24     3.906110e+05                  Sukhumvit apartment near Nana BTS   
25     3.930660e+05                        SKY 18 - 99 feet in the sky   
29     4.138240e+05          Lumphini 6 Central Oasis: Private EnSuite   
...             ...                                                ...   
20001  1.262870e+18  Sukhumvit 81 BTS Onnut 2minwalk - GP House Exp...   
20163  1.264970e+18  2BR-BTS Ekamai 300m-Sky Infinity Pool&Gym-2 pools   
22516  1.342520e+18  35平LOFT-367/近RCA/近火车夜市/近tonglor/近曼谷医院/近regent国际学校   
23061  1.354120e+18             Bangkok NaNa BTS/Free WiFi/ double bed   
24515  1.386820e+18         New! Swimming Pool/GYM/1 Bedroom loft/WiFI   

         host_id         host_name neighbourhood   latitude   longitude  \
7         545890             Henry   Khlong Toei  13.733780  100.563030   
21       1927968              Ivan        Sathon  13.720548  100.546970   
24        807406            Hollis   Khlong Toei  13.740520  100.552370   
25       1927968              Ivan        Sathon  13.720785  100.547241   
29       1927968              Ivan        Sathon  13.720548  100.546970   
...          ...               ...           ...        ...         ...   
20001  522083832  Girijesh Nandani  Phra Khanong  13.706309  100.605427   
20163  106371215                 昊   Khlong Toei  13.722046  100.580254   
22516   27721148              Lily   Huai Khwang  13.750460  100.598170   
23061  556988856             Qiang   Khlong Toei  13.739813  100.555433   
24515  487618699            Tomiya   Ratchathewi  13.753013  100.528685   

             room_type   price  minimum_nights  number_of_reviews last_review  \
7      Entire home/apt  5600.0              28                147  07-01-2020   
21     Entire home/apt   665.0               1                409  16-08-2025   
24     Entire home/apt   725.0               2                230  30-08-2025   
25     Entire home/apt   680.0               1                478  24-08-2025   
29     Entire home/apt   623.0               1                373  09-09-2025   
...                ...     ...             ...                ...         ...   
20001     Private room  1273.0               1                113  13-09-2025   
20163  Entire home/apt  4038.0               2                114  25-09-2025   
22516  Entire home/apt  1148.0               3                135  26-09-2025   
23061  Entire home/apt   883.0               1                126  18-09-2025   
24515  Entire home/apt  2429.0               1                115  25-09-2025   

       reviews_per_month  calculated_host_listings_count  availability_365  \
7                      0                               1               302   
21                     2                              63               275   
24                     1                               1               271   
25                     2                              63               361   
29                     2                              63               336   
...                  ...                             ...               ...   
20001                 11                              12               364   
20163                 16                               9               329   
22516                 17                              68               174   
23061                 18                               7               175   
24515                 23                              51               364   

       number_of_reviews_ltm  
7                          0  
21                         8  
24                        19  
25                        14  
29                        21  
...                      ...  
20001                    113  
20163                    114  
22516                    135  
23061  

In [26]:
df["last_review"].unique()

array(['17-09-2024', nan, '03-02-2014', ..., '25-10-2024', '29-10-2024',
       '19-09-2024'], dtype=object)

In [27]:
df["last_review"]=df["last_review"].fillna('18-12-2025')

In [28]:
df["last_review"].unique()

array(['17-09-2024', '18-12-2025', '03-02-2014', ..., '25-10-2024',
       '29-10-2024', '19-09-2024'], dtype=object)